### ISSUE TITLE
Larger text sizes please

### ISSUE THREAD

**Issue by gwgorman** [FirstLegoLeague/display#17]
Used this in two tournaments so far, and when this is projected on a big screen the text in the 'infinite scoring' table is very small. Tried using Ctrl+"+" to zoom the screen which helps, but then the clock is zoomed also.

**Comment by tovodeverett** [comment]
I'll second this as well - Ctrl+ works, but eventually the column headers begin to crop, and further along so do the point totals.  The clock also gets cropped pretty early on, but that's less of an issue if you also have a timer-only display up.  Again, I'll monitor this, and if it's still around in May I'll see if I can't work on the scaling behavior.

**Comment by alanggreen** [comment]
I'll add this to the backlog

**Comment by MitchTalmadge** [comment]
We ended up modifying the CSS in real time on our scoreboards to make them legible on our TVs. Zooming in made everything look terrible, especially the timer.

**Comment by idanstark42** [comment]
I'm very glad to hear you find a fix for your local problem. Who fixed it? This is exactly the kind of real-time, tech oriented thinking we're looking for in our development crew, and we'd love to talk to them. Maybe they could add their solution to the software, or even join the crew

**Comment by MitchTalmadge** [comment]
My friend Brian Ivie (@brianivie) came up with the idea and the fix. He's a great developer and is one of the most charitable people I know. 

I've been wanting to create a new FLL tournament manager for years and I'm really impressed with what you all have done here and happy that someone ran with the idea. I'd love to help out in my free time. You can look at my profile for a sample of my work. I'm a CS major at the University of Utah and I've been programming for my entire life, with a Facebook production engineering internship lined up this summer. I've been doing all the FLL tech work every year for the past 5 years at Entheos Academy in Kearns, Utah with the assistance of Brian Ivie.

**Comment by idanstark42** [comment]
That's really good to hear! If you want you can create a PR for this repository (the source code sits in `src` directory, and written in React) to add an option to enlarge the font, or to change the units of the fonts in the CSS (I think it's px now, maybe it should be `em`, `rem` or even `vh`, or different in each element) in order to solve the problem you're bringing up here.
If not, it'll just be appended to the backlog and we'll get to it soon enough. I want to emphasize that you joining us is not a requirement for the crew to solve issues you encounter.

**Comment by tovodeverett** [comment]
I suspect what they were doing is using Developer Tools in Chrome to modify the CSS on the browser end.  Here is what I just tried:

To adjust the table header font sizes, add a New Style Rule as follows:
```
.headers .cell.callout {
    font-size: 150%;
}
```

To adjust the table body font sizes, add a New Style Rule as follows:
```
.cell.callout {
    font-size: 200%;
}
```

To adjust the table body font sizes for the Team column only, add a New Style Rule as follows:
```
.cell.callout.auto {
    font-size: 180%;
}
```

To hide the text in the timer overlay (I can't get the overlay itself to disappear, because there is explicit style on the divs in the HTML that takes precedence over CSS):
```
.time {
    display: none;
}
```

**Comment by alanggreen** [comment]
@brianivie That's a great idea. Very much in the FLL spirit. We're looking to get more developers involved in the project as we have a whole list of bugfixes and improvements in our backlog.

**Comment by brianivie** [comment]
@alanggreen Thanks, I'll download it and check it out.  I would like to join the Git developers for FLL but can't seem to find out how (also the slack channel).  I'm also wondering if you wanted to apply for Google Summer of Code this year (great way to get even more developers).

**Comment by alanggreen** [comment]
@brianivie I added you to the firstlegoleague github organization

**Comment by idanstark42** [comment]
Very good to hear! I just wish to warn you that before approving your PR I'll ask you some questions to identify and justify the validity of the code. Don't take i5 the wrong way if it'll take a couple of iterations before it'll be merged, it happens most of the times here :)

**Comment by tovodeverett** [comment]
One design suggestion: aim for a solution that allows multiple scoreboards to display each with different font sizing (i.e. don't make the settings globally set by the Tournament setup).  Perhaps a pop-up DIV with controls for dynamically adjusting the local CSS to set font-sizes.

**Comment by MitchTalmadge** [comment]
What about something like this? 

![image](https://user-images.githubusercontent.com/8848080/51795304-f4135300-219d-11e9-9f3e-a356f2c8b956.png)

**Comment by gwgorman** [comment]
Closing...seems to be in the 2019 version now. Nice and thanks!
