### ISSUE TITLE
Make clock optional

### ISSUE THREAD

**Issue by gwgorman** [FirstLegoLeague/display#18]
Please add an option to turn off the Clock display in the scoring display. We had this showing in the pits and the clock / timer really isn't useful there.

**Comment by tovodeverett** [comment]
I second this motion.  For the Alaska Robot Rendezvous, we had two large flat-panel TVs displaying scores on the sides and a third one in the middle with the pure timer display.  In order to get the font of the score displays large enough to be legible, we had to bump the Chrome zoom pretty high, at which point the timer overlay was missing significant digits.  I had half-a-dozen requests to disable the time overlay, and each time I had to explain that given enough time to explore and understand the code-base (and to learn enough .NET - my core languages are T-SQL, Ruby, and Perl), yes, I could fix the issue, but it wasn't going to happen in the next 10 minutes!

I'm subscribing to this issue, and I'll stick a reminder in from May-ish - if it hasn't been resolved by then, I'll take a swing at putting together a pull request.

**Comment by alanggreen** [comment]
We're working on version v2018.2.0 at the moment, and we've added that
feature. It's still being tested but you are welcome to download and try it
out. Remember though that it's not production-ready (and the documentation
is not done yet) .The main feature added is a Status Display that is useful
when you have a full schedule. It tells you how well you are keeping to the
schedule.
https://ci.appveyor.com/api/buildjobs/by9p2apmt8v7lt16/artifacts/dist%2FFIRST_LEGO_League_Tournament_Management_System_Setup_2018.1.377_x64.exe

**Comment by tovodeverett** [comment]
Awesome - the Alaska season is largely over, but I think FIRST in Alaska is going to do a "corporate" one (get some adult teams to raise awareness), so hopefully the updated version will be out by then!

BTW, I must say I vastly prefer this .NET-based software to the National Instruments based version from last year.  It's a much cleaner install/uninstall, I doesn't drop as much random stuff all over the machine, etc.  It worked smoothly both for the qualifier and championship I supported, and all in all I'm very happy with it.

For the Alaska championships, we used a single gaming-class notebook to host the software and to drive HDMI through a splitter for the two main scoreboard displays.  We used 4 Chromebooks to handle score entry.  We used a 5th Chromebook for triggering the timer and displaying the timer via a mirrored HDMI output.  We used a 6th Chromebook for an HDMI feed of the scoreboard display into the main AV setup, which also had 5 video inputs from the tables and central camera.  The AV setup was used for the live stream as well as driving some monster super-bright (but somewhat low resolution) displays.  Our AV guy did a great job with that.  Finally, there was another notebook off in the judging deliberation room with the scoreboard display as well.  Compatibility with the Chromebooks is a huge win for us - the school district has loads of them and it's easy for us to get our hands on a cart with 18 of them.  That way when the batteries get low, we can just swap them out and stick them back in the charging cart.

Well done!!  There is always room for improvement, but at least from my perspective it is a great system, and I thoroughly appreciate the time and energy the team puts into developing it!

**Comment by alanggreen** [comment]
Thanks Toby.
One thing to mention - the technology is not .NET - it's node.js

**Comment by tovodeverett** [comment]
Now that's an embarrassing mistake on my part!  I must have glanced at vcruntime140.dll in the install directory and leaped to a completely off base assumption.  I apologize - there are some pretty dramatic variations between the alternatives in language (assuming C#) and architectural philosophies.

**Comment by gwgorman** [comment]
Closing...looks like clock is now optional! Thanks!
